#!/usr/bin/env node
// Reads the runtime sidecar assets and emits ts/assets.generated.ts so html.ts
// can import them statically. Keeps the bundle in dist/cli.js self-contained
// without forcing esbuild/vitest plugin gymnastics.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const sources = {
  CSS: join(root, "static", "style.css"),
  JS: join(root, "static", "script.js"),
  PAGE_TEMPLATE: join(root, "templates", "page.eta"),
  PLAN_TEMPLATE: join(root, "templates", "plan.eta"),
};

const lines = [
  "// AUTO-GENERATED by scripts/generate-assets.mjs. Do not edit by hand.",
  "// Run `npm run build:assets` (or `npm run build`) to regenerate.",
  "",
];

for (const [name, path] of Object.entries(sources)) {
  const contents = readFileSync(path, "utf8");
  lines.push(`export const ${name} = ${JSON.stringify(contents)};`);
}
lines.push("");

writeFileSync(join(root, "ts", "assets.generated.ts"), lines.join("\n"));
console.log(
  `Generated ts/assets.generated.ts (${Object.keys(sources).length} assets)`,
);
